// export default[
//     {
//         id:1,
//         postedOn : '2024-11-01',
//         title: 'iosDeveloper',
//         company: 'Apple',
//         type: 'Full Time',
//         experience: 'Mid-Level',
//         location: 'Remote',
//         skills :["SwiftUI", "UiKit", "Core Data"],
//         job_link:"https://www.apple.com/careers/in/",

//     },

//     {
//         id: 2,
//         postedOn: "2024-10-20",
//         title: "Frontend Developer",
//         type: "Full time",
//         location: "In-office",
//         experience: "Fresher",
//         company: "Amazon",
//         skills: ["Javascript", "Nextjs", "Tailwind CSS"],
//         job_link: "https://www.amazon.jobs/en/"
//     },
    

// {
//     id: 3,
//     postedOn : '2024-09-24',
//     title: "Backend Developer",
//     type: "Full time",
//     location: "In-office",
//     experience: "Fresher",
//     company: "Amazon",
//     skills: ["Python", "Django", "Flask"],
//     job_link: "https://www.amazon.jobs/en/",
// },

// {
//     id: 4,
//     postedOn : '2024-08-22',
//     title: "Android Developer",
//     type: "Full time",
//     location: "In-office",
//     experience: "Mid-Level",
//     company: "Google",
//     skills: ["Java", "Kotlin", "Android Studio"],
//     job_link: "https://www.google.com/about/careers/applications/jobs/results?src=Online%2FHouse%20Ads%2FBKWS_LOC2",  
// },
// {
//     id: 5,
//     postedOn : '2024-07-20',
//     title: 'Developer Advocate',
//     type: 'Part-Time',
//     experience: 'Junior-Level',
//     location: 'Remote',
//     company: 'Google',
//     skills :["Shell Scripting", "Nodejs", "Tailwind CSS", "Gitlab", "Java", "Javascript"],
//     job_link:"https://www.google.com/about/careers/applications/jobs/results?src=Online%2FHouse%20Ads%2FBKWS_LOC2",
// }

// ]

export default [
    {
        id: 1,
        postedOn: '2024-11-01',
        title: 'iOS Developer',
        company: 'Apple',
        type: 'Full Time',
        experience: 'Mid-Level',
        location: 'Remote',
        skills: ["SwiftUI", "UIKit", "Core Data"],
        job_link: "https://www.apple.com/careers/in/",
    },
    {
        id: 2,
        postedOn: "2024-10-20",
        title: "Frontend Developer",
        type: "Full Time",
        location: "In-office",
        experience: "Fresher",
        company: "Amazon",
        skills: ["JavaScript", "Next.js", "Tailwind CSS"],
        job_link: "https://www.amazon.jobs/en/",
    },
    {
        id: 3,
        postedOn: '2024-09-24',
        title: "Backend Developer",
        type: "Full Time",
        location: "In-office",
        experience: "Fresher",
        company: "Amazon",
        skills: ["Python", "Django", "Flask"],
        job_link: "https://www.amazon.jobs/en/",
    },
    {
        id: 4,
        postedOn: '2024-08-22',
        title: "Android Developer",
        type: "Full Time",
        location: "In-office",
        experience: "Mid-Level",
        company: "Google",
        skills: ["Java", "Kotlin", "Android Studio"],
        job_link: "https://www.google.com/about/careers/",
    },
    {
        id: 5,
        postedOn: '2024-07-20',
        title: 'Developer Advocate',
        type: 'Part-Time',
        experience: 'Junior-Level',
        location: 'Remote',
        company: 'Google',
        skills: ["Shell Scripting", "Node.js", "Tailwind CSS", "GitLab", "Java", "JavaScript"],
        job_link: "https://www.google.com/about/careers/",
    },
    {
        id: 6,
        postedOn: '2024-11-05',
        title: "Machine Learning Engineer",
        type: "Full Time",
        location: "Remote",
        experience: "Senior-Level",
        company: "Meta",
        skills: ["Python", "TensorFlow", "PyTorch", "Machine Learning"],
        job_link: "https://www.metacareers.com/",
    },
    {
        id: 7,
        postedOn: '2024-10-29',
        title: "Data Scientist",
        type: "Contract",
        location: "Remote",
        experience: "Mid-Level",
        company: "Netflix",
        skills: ["Python", "R", "Machine Learning", "SQL"],
        job_link: "https://jobs.netflix.com/",
    },
    {
        id: 8,
        postedOn: '2024-10-18',
        title: "Full Stack Developer",
        type: "Full Time",
        location: "Hybrid",
        experience: "Junior-Level",
        company: "Spotify",
        skills: ["React", "Node.js", "MongoDB", "Express"],
        job_link: "https://www.spotifyjobs.com/",
    },
    {
        id: 9,
        postedOn: '2024-10-15',
        title: "UX/UI Designer",
        type: "Part-Time",
        location: "Remote",
        experience: "Mid-Level",
        company: "Tesla",
        skills: ["Figma", "Sketch", "Adobe XD", "UI/UX Design"],
        job_link: "https://www.tesla.com/careers/",
    },
    {
        id: 10,
        postedOn: '2024-09-30',
        title: "Cloud Engineer",
        type: "Full Time",
        location: "In-office",
        experience: "Senior-Level",
        company: "Microsoft",
        skills: ["AWS", "Azure", "GCP", "Docker", "Kubernetes"],
        job_link: "https://careers.microsoft.com/",
    },
    {
        id: 11,
        postedOn: '2024-09-01',
        title: "Blockchain Developer",
        type: "Contract",
        location: "Remote",
        experience: "Mid-Level",
        company: "Coinbase",
        skills: ["Solidity", "Ethereum", "Smart Contracts", "Web3.js"],
        job_link: "https://www.coinbase.com/careers",
    },
    {
        id: 12,
        postedOn: '2024-08-18',
        title: "DevOps Engineer",
        type: "Full Time",
        location: "Hybrid",
        experience: "Senior-Level",
        company: "LinkedIn",
        skills: ["CI/CD", "Docker", "Kubernetes", "Jenkins", "AWS"],
        job_link: "https://careers.linkedin.com/",
    },
    {
        id: 13,
        postedOn: '2024-12-24',
        title: "Security Engineer",
        type: "Full Time",
        location: "Remote",
        experience: "Mid-Level",
        company: "Cisco",
        skills: ["Cybersecurity", "Network Security", "Python", "SIEM"],
        job_link: "https://jobs.cisco.com/",
    },
    
];
